name: Build Arch Package (Git)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build with makepkg
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Install base dependencies
        run: |
          pacman -Sy --noconfirm archlinux-keyring
          pacman -Syu --noconfirm base-devel git sudo wget zsync java-environment

      - name: Create build user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fix permissions
        run: chown -R builder:builder .

      - name: Build package (makepkg -si)
        run: |
          sudo -u builder bash <<'EOF'
          set -e
          git clone https://aur.archlinux.org/yay-bin.git
          cd yay-bin
          makepkg -si --noconfirm
          yay -S jdk-openjdk-wakefield --noconfirm
          cd ..
          cd pkg/jpexs
          makepkg -si --noconfirm
          EOF

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: arch-package
          path: |
            pkg/jpexs/*.pkg.tar.zst
